repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.6
  hooks:
  - id: ruff-format
    description: "Ruff formatting"
    types_or: [python, pyi, jupyter]
  - id: ruff
    description: "Ruff linting"
    types_or: [python, pyi, jupyter]
    args: [--fix, --exit-non-zero-on-fix]
